---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-ini-volume
  labels:
    app: php-ini-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi 
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/data/php-ini"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-ini-volume-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  selector: 
    matchLabels: 
      app: php-ini-volume       

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-app-volume
  labels:
    app: php-app-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi 
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/data/php-app"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-app-volume-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  selector: 
    matchLabels: 
      app: php-app-volume     

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-volume
  labels:
    app: nginx-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi 
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/data/nginx/conf"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-volume-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  selector: 
    matchLabels: 
      app: nginx-volume    


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d"
            name: nginx-volume
          - mountPath: "/var/www"
            name: php-app-volume
        env:
        - name: pg_primary_node_fqdn
          value: primary.default.svc.cluster.local


      - name: fpm
        image: allansimon/php7-fpm-postgresql
        ports:
        - containerPort: 9000
        volumeMounts:
          - mountPath: "/usr/local/etc/php"
            name: php-ini-volume
          - mountPath: "/var/www"
            name: php-app-volume   
      volumes:
        - name: php-ini-volume
          persistentVolumeClaim:
            claimName: php-ini-volume-pvc  
        - name: php-app-volume
          persistentVolumeClaim:
            claimName: php-app-volume-pvc
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: nginx-volume-pvc
        
       
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:    
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: fpm
  labels:
    app: frontend
spec:    
  type: ClusterIP
  ports:
    - targetPort: 9000
      port: 9000
  selector:
    app: frontend