apiVersion: v1
kind: Pod
metadata:
  name: "{{.Values.container.name.primary}}"
  labels:
    name: "{{.Values.container.name.primary}}"
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{.Release.Service | quote }}
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{.Release.Name | quote }}
    # This makes it easy to audit chart usage.
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
{{/*
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
*/}}    
spec:
  # This shows how to use a simple value. This will look for a passed-in value
  # called restartPolicy. If it is not found, it will use the default value.
  # {{default "Never" .restartPolicy}} is a slightly optimized version of the
  # more conventional syntax: {{.restartPolicy | default "Never"}}
  restartPolicy: {{default "Never" .Values.restartPolicy}}
  containers:
  - name: {{.Values.container.name.primary}}
    image: "{{.Values.image.repository}}/{{.Values.image.container}}:{{.Values.image.tag}}"
    ports:
    - containerPort: {{.Values.container.port}}
    env:
    - name: PGHOST
      value: /tmp
    - name: PG_PRIMARY_USER
      value: primaryuser
    - name: PG_MODE
      value: primary
    - name: PG_PRIMARY_PORT
      value: "{{.Values.container.port}}"
    - name: PG_PRIMARY_PASSWORD
      value: "{{.Values.credentials.primary}}"
    - name: PG_USER
      value: testuser
    - name: PG_PASSWORD
      value: "{{.Values.credentials.user}}"
    - name: PG_DATABASE
      value: blacklisted
    - name: PG_ROOT_PASSWORD
      value: "{{.Values.credentials.root}}"
    - name: MODE
      value: "postgres"      
    resources:
      requests:
        cpu: {{ .Values.resources.cpu }}
        memory: {{ .Values.resources.memory }}
    volumeMounts:
    - mountPath: /pgdata
      name: pgdata
    - mountPath: /backup
      name: backup
      readOnly: true
    - mountPath: /pguser
      name: pguser-volume
    - mountPath: /pgprimary
      name: pgprimary-volume
    - mountPath: /pgroot
      name: pgroot-volume
  volumes:
  - emptyDir: {}
    name: pgdata
  - emptyDir: {}
    name: backup
  - name: pguser-volume
    secret:
     secretName: pguser-secret
  - name: pgprimary-volume
    secret:
     secretName: pgprimary-secret
  - name: pgroot-volume
    secret:
     secretName: pgroot-secret

---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: postgres-migration
        image: jbergknoff/postgresql-client
        command: ["/bin/sh", "-c"]
        args: ["export PGPASSWORD=password; psql -h primary -U postgres blacklisted -c 'CREATE TABLE public.blacklisted (
      location varchar NOT NULL,
      ip_address varchar NOT NULL,
      datetime timestamp NOT NULL DEFAULT NOW()
    )'"]
      restartPolicy: Never
  backoffLimit: 3